import { Skill, User } from '@/shared/types'
import { SkillCategory } from './types'

export const skillsData: SkillCategory[] = [
  {
    id: 'business',
    title: 'Бизнес и карьера',
    items: [
      'Управление командой',
      'Маркетинг и реклама',
      'Продажи и переговоры',
      'Личный бренд',
      'Резюме и собеседование',
      'Тайм-менеджмент',
      'Проектное управление',
      'Предпринимательство',
    ],
  },
  {
    id: 'creativity',
    title: 'Творчество и искусство',
    items: [
      'Рисование и иллюстрация',
      'Фотография',
      'Видеомонтаж',
      'Музыка и звук',
      'Актёрское мастерство',
      'Креативное письмо',
      'Арт-терапия',
      'Декор и DIY',
    ],
  },
  {
    id: 'languages',
    title: 'Иностранные языки',
    items: [
      'Английский',
      'Французский',
      'Испанский',
      'Немецкий',
      'Китайский',
      'Японский',
      'Подготовка к экзаменам (IELTS, TOEFL)',
    ],
  },
  {
    id: 'education',
    title: 'Образование и развитие',
    items: [
      'Личностное развитие',
      'Навыки обучения',
      'Когнитивные техники',
      'Скорочтение',
      'Навыки преподавания',
      'Коучинг',
    ],
  },
  {
    id: 'health',
    title: 'Здоровье и лайфстайл',
    items: [
      'Йога и медитация',
      'Питание и ЗОЖ',
      'Ментальное здоровье',
      'Осознанность',
      'Физические тренировки',
      'Сон и восстановление',
      'Баланс жизни и работы',
    ],
  },
  {
    id: 'home',
    title: 'Дом и уют',
    items: [
      'Уборка и организация',
      'Домашние финансы',
      'Приготовление еды',
      'Домашние растения',
      'Ремонт',
      'Хранение вещей',
    ],
  },
]

export const citiesData: string[] = [
  'Москва',
  'Санкт-Петербург',
  'Новосибирск',
  'Екатеринбург',
  'Казань',
  'Нижний Новгород',
  'Челябинск',
  'Самара',
  'Омск',
  'Ростов-на-Дону',
  'Уфа',
  'Красноярск',
  'Пермь',
  'Воронеж',
  'Волгоград',
  'Краснодар',
  'Саратов',
  'Тюмень',
  'Тольятти',
  'Ижевск',
]

// ─── Добавляем моковых пользователей ───────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Алексей Смирнов',
    email: 'alexey@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=11',
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'u2',
    name: 'Елена Васильева',
    email: 'elena@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    createdAt: '2025-01-20T12:30:00Z',
  },
  {
    id: 'u3',
    name: 'Дмитрий Ковалев',
    email: 'dmitry@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    createdAt: '2025-02-01T09:15:00Z',
  },
  {
    id: 'u4',
    name: 'Анна Морозова',
    email: 'anna@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
    createdAt: '2025-02-10T14:00:00Z',
  },
  {
    id: 'u5',
    name: 'Игорь Кузнецов',
    email: 'igor@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
    createdAt: '2025-02-15T16:45:00Z',
  },
  {
    id: 'u6',
    name: 'Ольга Попова',
    email: 'olga@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=20',
    createdAt: '2025-03-01T11:20:00Z',
  },
  {
    id: 'u7',
    name: 'Максим Громов',
    email: 'maxim@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    createdAt: '2025-03-05T08:10:00Z',
  },
  {
    id: 'u8',
    name: 'София Лебедева',
    email: 'sofia@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=24',
    createdAt: '2025-03-10T15:30:00Z',
  },
  {
    id: 'u9',
    name: 'Артем Мельников',
    email: 'artem@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
    createdAt: '2025-03-12T17:00:00Z',
  },
  {
    id: 'u10',
    name: 'Мария Федорова',
    email: 'maria@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?img=32',
    createdAt: '2025-03-15T13:40:00Z',
  },
]

// ─── Добавляем моковые навыки (строго с именами из skillsData) ─────────

export const mockSkills: Skill[] = [
  // u1 (Алексей): Обучает проектному управлению, хочет выучить Английский
  {
    id: 's1',
    title: 'Проектное управление',
    description: 'Обучу ведению проектов и Agile-методологиям',
    type: 'teach',
    category: 'business',
    tags: ['Проектное управление', 'Бизнес'],
    imageUrl: null,
    authorId: 'u1',
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 's2',
    title: 'Английский',
    description: 'Ищу репетитора по разговорному английскому',
    type: 'learn',
    category: 'languages',
    tags: ['Английский', 'Языки'],
    imageUrl: null,
    authorId: 'u1',
    createdAt: '2025-01-16T10:05:00Z',
  },

  // u2 (Елена): Обучает Рисованию, хочет выучить Маркетинг и рекламу
  {
    id: 's3',
    title: 'Рисование и иллюстрация',
    description: 'Академический рисунок и цифровой арт',
    type: 'teach',
    category: 'creativity',
    tags: ['Рисование и иллюстрация', 'Арт'],
    imageUrl: null,
    authorId: 'u2',
    createdAt: '2025-01-21T11:00:00Z',
  },
  {
    id: 's4',
    title: 'Маркетинг и реклама',
    description: 'Хочу научиться продвигать свои работы',
    type: 'learn',
    category: 'business',
    tags: ['Маркетинг и реклама'],
    imageUrl: null,
    authorId: 'u2',
    createdAt: '2025-01-21T11:10:00Z',
  },

  // u3 (Дмитрий): Обучает Тайм-менеджменту
  {
    id: 's5',
    title: 'Тайм-менеджмент',
    description: 'Поставлю систему планирования задач',
    type: 'teach',
    category: 'business',
    tags: ['Тайм-менеджмент'],
    imageUrl: null,
    authorId: 'u3',
    createdAt: '2025-02-02T10:00:00Z',
  },

  // u4 (Анна): Обучает Английскому, хочет выучить Приготовление еды
  {
    id: 's6',
    title: 'Английский',
    description: 'Носитель языка, подготовлю к интервью',
    type: 'teach',
    category: 'languages',
    tags: ['Английский'],
    imageUrl: null,
    authorId: 'u4',
    createdAt: '2025-02-11T09:00:00Z',
  },
  {
    id: 's7',
    title: 'Приготовление еды',
    description: 'Хочу освоить базовую кулинарию',
    type: 'learn',
    category: 'home',
    tags: ['Приготовление еды'],
    imageUrl: null,
    authorId: 'u4',
    createdAt: '2025-02-11T09:15:00Z',
  },

  // u5 (Игорь): Обучает Фотографии, хочет Скорочтение
  {
    id: 's8',
    title: 'Фотография',
    description: 'Портретная и пейзажная съемка',
    type: 'teach',
    category: 'creativity',
    tags: ['Фотография'],
    imageUrl: null,
    authorId: 'u5',
    createdAt: '2025-02-16T14:00:00Z',
  },
  {
    id: 's9',
    title: 'Скорочтение',
    description: 'Мечтаю читать по книге в день',
    type: 'learn',
    category: 'education',
    tags: ['Скорочтение'],
    imageUrl: null,
    authorId: 'u5',
    createdAt: '2025-02-16T14:20:00Z',
  },

  // u6 (Ольга): Обучает Йоге и медитации
  {
    id: 's10',
    title: 'Йога и медитация',
    description: 'Практики расслабления и осознанности',
    type: 'teach',
    category: 'health',
    tags: ['Йога и медитация'],
    imageUrl: null,
    authorId: 'u6',
    createdAt: '2025-03-02T10:00:00Z',
  },

  // u7 (Максим): Обучает Французскому, хочет Видеомонтаж
  {
    id: 's11',
    title: 'Французский',
    description: 'Французский с нуля для путешествий',
    type: 'teach',
    category: 'languages',
    tags: ['Французский'],
    imageUrl: null,
    authorId: 'u7',
    createdAt: '2025-03-06T12:00:00Z',
  },
  {
    id: 's12',
    title: 'Видеомонтаж',
    description: 'Учусь монту в Premiere Pro',
    type: 'learn',
    category: 'creativity',
    tags: ['Видеомонтаж'],
    imageUrl: null,
    authorId: 'u7',
    createdAt: '2025-03-06T12:30:00Z',
  },

  // u8 (София): Обучает Личному бренду
  {
    id: 's13',
    title: 'Личный бренд',
    description: 'Упаковка экспертности в соцсетях',
    type: 'teach',
    category: 'business',
    tags: ['Личный бренд'],
    imageUrl: null,
    authorId: 'u8',
    createdAt: '2025-03-11T16:00:00Z',
  },

  // u9 (Артем): Обучает Ремонту, хочет Физические тренировки
  {
    id: 's14',
    title: 'Ремонт',
    description: 'Советы по отделке и выбору материалов',
    type: 'teach',
    category: 'home',
    tags: ['Ремонт'],
    imageUrl: null,
    authorId: 'u9',
    createdAt: '2025-03-13T10:00:00Z',
  },
  {
    id: 's15',
    title: 'Физические тренировки',
    description: 'Ищу тренера по силовым упражнениям',
    type: 'learn',
    category: 'health',
    tags: ['Физические тренировки'],
    imageUrl: null,
    authorId: 'u9',
    createdAt: '2025-03-13T10:30:00Z',
  },

  // u10 (Мария): Обучает Домашним растениям
  {
    id: 's16',
    title: 'Домашние растения',
    description: 'Все об уходе за комнатными цветами',
    type: 'teach',
    category: 'home',
    tags: ['Домашние растения'],
    imageUrl: null,
    authorId: 'u10',
    createdAt: '2025-03-16T11:00:00Z',
  },
]
